/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 *        
 */

import React, { Component } from 'react';
import { Platform, SafeAreaView, StyleSheet, Text, View, Button} from 'react-native';
import FlybitsConcierge, { connect, sendBatteryContext } from 'react-native-flybits-concierge-react-native';
import { NativeModules } from 'react-native';
const { FlybitsModule } = NativeModules;

export default class App extends Component<{}> {
  render() {
    return (
      <SafeAreaView style={styles.container}>
        <Button title='Connect' styles={{ flex: 1 }} onPress={() => {
          Platform.select({
            ios: () => connect(),
            android: () => FlybitsModule.flybitsConnect('testName', 'testLocation')
          })();
        }} />
        <Button title='SendBatteryContext' styles={{ flex: 1 }} onPress={() => {
          Platform.select({
            ios: () =>   sendBatteryContext(),
            android: () => FlybitsModule.sendBattery()
          })();
        
        }} />
        
        <FlybitsConcierge style={{flex:1, width: "100%"}}/>
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex:1,
    flexDirection: "column",
    backgroundColor: '#333333',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
